[package]
name = "nixtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26.1"
log = "0.4.17"
file = "1.1.2"